// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZuJn9DIzt3Yo2Yag1KqAgxV83fAq0XA',
    appId: '1:397441632323:web:86fca1775d54ba2105ecf6',
    messagingSenderId: '397441632323',
    projectId: 'todofirebase-9f704',
    authDomain: 'todofirebase-9f704.firebaseapp.com',
    storageBucket: 'todofirebase-9f704.appspot.com',
    measurementId: 'G-H59T7533S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV9JC5iRqcXPOi1O1ABt4PWY-cYQ6m4xY',
    appId: '1:397441632323:android:864730488e6ae32e05ecf6',
    messagingSenderId: '397441632323',
    projectId: 'todofirebase-9f704',
    storageBucket: 'todofirebase-9f704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe7rZx5pw95P6gPdgVdhjjZC3ZVkzQJz0',
    appId: '1:397441632323:ios:03404a974b51529905ecf6',
    messagingSenderId: '397441632323',
    projectId: 'todofirebase-9f704',
    storageBucket: 'todofirebase-9f704.appspot.com',
    iosClientId: '397441632323-55g2k07241sqoqnt69etuag8ft4paqa3.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe7rZx5pw95P6gPdgVdhjjZC3ZVkzQJz0',
    appId: '1:397441632323:ios:03404a974b51529905ecf6',
    messagingSenderId: '397441632323',
    projectId: 'todofirebase-9f704',
    storageBucket: 'todofirebase-9f704.appspot.com',
    iosClientId: '397441632323-55g2k07241sqoqnt69etuag8ft4paqa3.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsdo',
  );
}
